/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/ping": {
    /**
     * 挙動を確認
     * @description 挙動を確認するためのものです。
     */
    get: operations["ping"];
  };
  "/tasks": {
    /**
     * 例文を取得
     * @description 例文を取得
     */
    get: operations["getTasks"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ping: {
      /** @example pong */
      message?: string;
    };
    task: {
        /** @example 東京科学大学 */
        content?: string;
        /** @example とうきょうかがくだいがく */
        yomi?: string;
        /** @example https://q.trap.jp/api/v3/public/icon/ramdos */
        iconUri?: string;
        /** @example あんこ🌱 */
        authorDisplayName?: string;
        /** @example 21B */
        grade?: string;
        /** @example anko */
        authorName?: string;
        /**
         * Format: date-time
         * @example 2006/01/02 15:04
         */
        updatedAt?: string;
        /** @example https://q.trap.jp/messages/25e071cd-45fa-4593-99f4-399e29a2c827 */
        citated?: string;
        /** @example https://q.trap.jp/files/b8050d58-17d9-4c84-a910-b670cb3b77bc */
        image?: string;
        stamps?: components["schemas"]["stamp"];
      }[];
    /** MessageStamp */
    stamp: {
        /**
         * Format: uuid
         * @description ユーザーUUID
         */
        stampId?: string;
        /**
         * Format: integer
         * @description スタンプ数
         */
        count?: number;
      }[];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * 挙動を確認
   * @description 挙動を確認するためのものです。
   */
  ping: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ping"];
        };
      };
    };
  };
  /**
   * 例文を取得
   * @description 例文を取得
   */
  getTasks: {
    parameters: {
      query: {
        /** @description 難易度 */
        level: number;
        /** @description 件数 */
        count: number;
        /** @description 過激な内容を含むか */
        isSensitive: boolean;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["task"];
        };
      };
      /** @description 正しくないリクエスト */
      400: {
        content: never;
      };
    };
  };
}
